export const certificationData = [
  {
    certName: "Basic Image Classification with Tensorflow",
    certDate: "November 2022",
    // certDescription: "Certification Description",
    tags: ["Python", "AI/ML", "Tensorflow"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/3FV7FTUKVSXT",
  },
  {
    certName: "Conduct UX Research and Test Early Concepts",
    certDate: "August 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/DENSCHJSYZTG",
  },
  {
    certName: "Create High-Fidelity Designs and Prototypes in Figma",
    certDate: "August 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/FQF88WZWBMXU",
  },
  {
    certName: "Google UX Design Specialization",
    certDate: "August 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/specialization/certificate/ECJ2NEQYXD7L",
  },
  {
    certName: "Responsive Web Design in Adobe XD",
    certDate: "August 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/WARYEZXYW5T8",
  },
  {
    certName: "Build Wireframes & Low-Fidelity Prototypes",
    certDate: "July 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/D2Z7ML927C8J",
  },
  {
    certName: "Start the UX Design Process",
    certDate: "July 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/QXNBC8BBQHP4",
  },
  {
    certName: "Foundations of UX Design",
    certDate: "June 2022",
    // certDescription: "Certification Description",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/C88Q4U8WMKE7",
  },
  {
    certName: "Google Cloud Baseline: Infrastructure",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["Cloud"],
    cred: "https://www.cloudskillsboost.google/public_profiles/4ca3bcc5-3ee9-4da9-8234-163cf9c4bcbd/badges/2112640",
  },
  {
    certName: "Command Line Basics in Linux",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["Linux"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/AFSHUBTE9VC3",
  },
  {
    certName: "Google Cloud Essentials",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["Cloud"],
    cred: "https://www.cloudskillsboost.google/public_profiles/4ca3bcc5-3ee9-4da9-8234-163cf9c4bcbd/badges/2111736",
  },
  {
    certName: "IBM Applied AI Specialization",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["AI/ML", "IBM"],
    cred: "https://www.coursera.org/account/accomplishments/specialization/certificate/9AM9LT39GVYU",
  },
  {
    certName: "Introduction to Data Analysis using Excel",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["Data Analysis"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/GX2EAMQBTKZU",
  },
  {
    certName: "Python Project for AI & Application Development",
    certDate: "May 2022",
    // certDescription: "Certification Description",
    tags: ["Python", "AI/ML"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/HAPN9CU9Q22X",
  },
  {
    certName: "Ethical Hacking Fundamentals",
    certDate: "March 2022",
    // certDescription: "Certification Description",
    tags: ["Cyber Security"],
    cred: "https://olympus1.mygreatlearning.com/course_certificate/DFFNTWDL",
  },
  {
    certName: "Firewall and Security",
    certDate: "March 2022",
    // certDescription: "Certification Description",
    tags: ["Cyber Security"],
    cred: "https://olympus1.mygreatlearning.com/course_certificate/WSADWSBU",
  },
  {
    certName: "Introduction to Psychology",
    certDate: "March 2022",
    // certDescription: "Certification Description",
    tags: ["Psychology"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/UWMVR9KRR4B2",
  },
  {
    certName: "Python for Data Science, AI & Development",
    certDate: "March 2022",
    // certDescription: "Certification Description",
    tags: ["Data Analysis", "Python", "AI/ML"],
    cred: "https://www.coursera.org/account/accomplishments/certificate/CNXURQKMKMBQ",
  },
];