export const projectData = [
  {
    projectName: "Machine Learning Basics",
    // projectDate: "Jun 2020",
    projectDescription: "This repository serves as a beginner's guide to machine learning algorithms, providing implementations and examples for various fundamental algorithms.",
    tags: ["Python", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/machine-learning-basics",
  },
  {
    projectName: "Personal Website",
    // projectDate: "Jun 2020",
    projectDescription: "Creating a personal portfolio website for myself.",
    tags: ["HTML/CSS"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/akshit-g.github.io",
  },
  {
    projectName: "Django Blog",
    // projectDate: "Jun 2020",
    projectDescription: "Creating a blog in Django with basic CRUD functions and authentication.",
    tags: ["Python", "Django"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/django-blog-tutorial",
  },
  {
    projectName: "Cryptography Algorithms",
    // projectDate: "Jun 2020",
    projectDescription: "This repository contains implementations of various encryption algorithms in different programming languages namely RSA, SHA, DES, SSH, AES, Caesar Cipher",
    tags: ["Java"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/crypto-algorithms",
  },
  {
    projectName: "ASL Recognition",
    // projectDate: "Jun 2020",
    projectDescription: "Build a convolutional neural network to classify images of letters from American Sign Language",
    tags: ["Python", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/ASL_Recognition",
  },
  {
    projectName: "One Stop Solution",
    // projectDate: "Jun 2020",
    projectDescription: "An app that serves as a one-stop-shop for all the nearby restaurants, pharmacies, hostels, PGs, and doctors near our college campus can be a great way to help students find and access the services they need.",
    tags: ["Dart", "Flutter"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/one-stop-solution",
  },
  {
    projectName: "Technova Bootcamp",
    // projectDate: "Jun 2020",
    projectDescription: "Machine Learning session held as a part of Technova Bootcamp at UPES GDSC",
    tags: ["Python", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/Technova-ML",
  },
  {
    projectName: "UPES NSS Website",
    // projectDate: "Jun 2020",
    projectDescription: "A website designed and made in ReactJS for the NSS club at UPES",
    tags: ["HTML/CSS", "JavaScript", "ReactJS"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/UPES_NSS",
  },
  {
    projectName: "Linear Regression in R",
    // projectDate: "Jun 2020",
    projectDescription: "Multiple Linear Regression in R on the marketing dataset.",
    tags: ["R"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/linear-regression-project",
  },
  {
    projectName: "Snake Game",
    // projectDate: "Jun 2020",
    projectDescription: "Clone of the classic snake game made using python",
    tags: ["Python"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/snake_game",
  },
  {
    projectName: "ENG-ESP Translator",
    // projectDate: "Jun 2020",
    projectDescription: "English-Spanish language translator built using Flask framework in python.",
    tags: ["Python", "Flask"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/rlkee-flaskproject-ENG-ESP",
  },
  {
    projectName: "B. Tech CSE 1st Year",
    // projectDate: "Jun 2020",
    projectDescription: "Files related to the 1st year of B. Tech CSE",
    tags: ["Python", "C", "Java"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/imagine-chetas-coding",
  },
  {
    projectName: "ENG-FR Translator",
    // projectDate: "Jun 2020",
    projectDescription: "ENG-FR language translator made using flask framework",
    tags: ["Python", "Flask"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/xzceb-flask_eng_fr",
  },
  {
    projectName: "IBM Discovery and Watson",
    // projectDate: "Jun 2020",
    projectDescription: "Adding Discovery to IBM Watson Chatbot (Coursera Course Applied AI)",
    tags: ["HTML", "JavaScript"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/ncehu-AppliedAI_6_Module4",
  },
  {
    projectName: "Logistic Regression from Scratch",
    // projectDate: "Jun 2020",
    projectDescription: "Logistic Regression from Scratch in Python",
    tags: ["Python", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/logistic-regression-clone",
  },
  {
    projectName: "Dog Image Classifier",
    // projectDate: "Jun 2020",
    projectDescription: "Dog Image Classifier made using TensorFlow and Keras",
    tags: ["Python", "Tensorflow", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/dog-image-classifier",
  },
  {
    projectName: "MNIST Image Classifier",
    // projectDate: "Jun 2020",
    projectDescription: "Create and train a model that takes an image of a hand written digit as input and predicts the class of that digit (predicts the digit)",
    tags: ["Python", "Tensorflow", "AI/ML"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/tf-image-classifier",
  },
  {
    projectName: "Hello React",
    // projectDate: "Jun 2020",
    projectDescription: "React basics",
    tags: ["HTML", "JavaScript", "ReactJS"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/hello-react",
  },
  {
    projectName: "Coursera UI/UX",
    // projectDate: "Jun 2020",
    projectDescription: "Coursera coursework for UI/UX professional certification",
    tags: ["UI/UX", "Figma"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/coursera_ui-ux",
  },
  {
    projectName: "Guess the Number",
    // projectDate: "Jun 2020",
    projectDescription: "A number guessing game is a simple guessing game where a user is supposed to guess a number between 0 and N in a maximum of 10 attempts.",
    tags: ["Python"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/guess_the_number",
  },
  {
    projectName: "Madlibs Generator",
    // projectDate: "Jun 2020",
    projectDescription: "MadLibs is a game in which you write a story with missing words in it; then, you can ask another player to fill in the blanks.",
    tags: ["Python"],
    // link: "https://project.herokuapp.com/",
    repo: "https://github.com/akshit-g/madlibs_game_generator",
  },
];